AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10
